[package]
name = "i6"
version = "0.1.5" # prepare_release.sh
edition = "2021"
license = "MIT"
authors = ["kruserr"]
readme = "README.md"
repository = "https://github.com/kruserr/i6"
description = "A collection of tools"
keywords = ["cli", "terminal", "utility", "tool", "command"]
categories = ["command-line-interface", "command-line-utilities", "development-tools"]

[dependencies]
clap = { version = "4", features = ["cargo"] }
